- name: Install AstroNVim
  hosts: localhost

  tasks:
    - name: Check if nerd-fonts is installed
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          fc-list | grep Inconsolata
        executable: /bin/bash
      register: nerd_fonts_installed
      changed_when: false
      failed_when: false

    - name: Install nerd-fonts
      when: nerd_fonts_installed.stdout == ""
      block:
        - name: Create ~/.local/share/fonts/NerdFonts
          ansible.builtin.file:
            path: ~/.local/share/fonts/NerdFonts
            state: directory
            mode: "0755"

        - name: Download and unpack Inconsolata nerd-fonts
          ansible.builtin.unarchive:
            src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Inconsolata.tar.xz
            dest: ~/.local/share/fonts/NerdFonts
            remote_src: true

        - name: Update font cache
          ansible.builtin.shell:
            cmd: fc-cache -f -v
            executable: /bin/bash
          changed_when: false
          failed_when: false

    - name: Check if NeoVim is installed
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ~/apps/nvim/nvim.appimage --version
        executable: /bin/bash
      register: nvim_installed
      changed_when: false
      failed_when: false

    - name: Install NeoVim as appimage
      when: nvim_installed.rc != 0
      block:

        - name: Enable universe repository
          become: true
          ansible.builtin.apt_repository:
            repo: "{{ item }}"
            update_cache: yes
          loop:
            - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
            - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"

        - name: Install libfuse2 # don't install fuse on >= 22.04
          become: true
          ansible.builtin.apt:
            name: libfuse2
            state: present

        - name: Create ~/apps/nvim
          ansible.builtin.file:
            path: ~/apps/nvim
            state: directory
            mode: "0755"

        - name: Download NeoVim appimage
          ansible.builtin.get_url:
            url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
            dest: ~/apps/nvim/nvim.appimage
            mode: "0764"
          
        - name: Add nvim alias
          ansible.builtin.lineinfile:
            path: ~/.zshrc
            line: "alias nvim='~/apps/nvim/nvim.appimage'"
            state: present