- name: Install cheat on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  vars:
    cheat_version: "4.4.0"
    download_url: "https://github.com/cheat/cheat/releases/download/{{ cheat_version }}/cheat-linux-amd64.gz"
    temp_file: "/tmp/cheat-linux-amd64.gz"
    executable_file: "/tmp/cheat-linux-amd64"

  tasks:
    - name: Check if cheat is already installed
      ansible.builtin.command:
        cmd: "cheat -v"
      register: cheat_version_output
      failed_when: false
      changed_when: false

    - name: Install cheat
      when: cheat_version_output.rc != 0
      block:

        - name: Download cheat binary
          ansible.builtin.get_url:
            url: "{{ download_url }}"
            dest: "{{ temp_file }}"
            mode: '0644'

        - name: Extract cheat binary
          ansible.builtin.command:
            cmd: "gunzip {{ temp_file }}"
            creates: "{{ executable_file }}"

        - name: Make cheat binary executable
          ansible.builtin.file:
            path: "{{ executable_file }}"
            mode: '0755'

        - name: Move cheat binary to /usr/local/bin
          ansible.builtin.command:
            cmd: "mv {{ executable_file }} /usr/local/bin/cheat"
            removes: "{{ executable_file }}"
