- name: Install cheat on Ubuntu
  hosts: localhost
  become: false

  vars:
    cheat_version: "4.4.0"
    download_url: "https://github.com/cheat/cheat/releases/download/{{ cheat_version }}/cheat-linux-amd64.gz"
    temp_file: "/tmp/cheat-linux-amd64.gz"
    executable_file: "/tmp/cheat-linux-amd64"

  tasks:
    - name: Check if cheat is already installed
      ansible.builtin.command:
        cmd: "cheat -v"
      register: cheat_version_output
      failed_when: false
      changed_when: false

    - name: Install cheat
      when: cheat_version_output.rc != 0
      block:

        - name: Download cheat binary
          ansible.builtin.get_url:
            url: "{{ download_url }}"
            dest: "{{ temp_file }}"
            mode: '0644'

        - name: Extract cheat binary
          ansible.builtin.command:
            cmd: "gunzip {{ temp_file }}"
            creates: "{{ executable_file }}"

        - name: Make cheat binary executable
          ansible.builtin.file:
            path: "{{ executable_file }}"
            mode: '0755'

        - name: Move cheat binary to /usr/local/bin
          become: true
          ansible.builtin.command:
            cmd: "mv {{ executable_file }} /usr/local/bin/cheat"
            removes: "{{ executable_file }}"

        - name: Clone cheat community repository # noqa: latest
          ansible.builtin.git:
            repo: "https://github.com/cheat/cheatsheets.git"
            dest: "~/.config/cheat/cheatsheets/community"

        - name: Run cheat to generate config file and directories
          ansible.builtin.shell:
            cmd: |
              mkdir -p ~/.config/cheat
              mkdir -p ~/.config/cheat/cheatsheets/personal
              cheat --init > ~/.config/cheat/conf.yml
            creates: "~/.config/cheat/conf.yml"

        - name: Fix pager in config file
          ansible.builtin.lineinfile:
            path: ~/.config/cheat/conf.yml
            regexp: '^pager'
            line: 'pager: less -FRX'
