# ansible task for downloading and installing Chrome
- name: Download and install Chrome
  hosts: localhost

  tasks:

    - name: Check if google-chrome binary exists
      ansible.builtin.stat:
        path: /usr/bin/google-chrome
      register: chrome_binary

    - name: Download and install Chrome
      when: not chrome_binary.stat.exists
      block:
        - name: Download Chrome
          ansible.builtin.get_url:
            url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
            dest: "/tmp/google-chrome-stable_current_amd64.deb"
            mode: "0644"
            validate_certs: false
            force: true
          register: chrome_download
          until: chrome_download is succeeded
          retries: 5
          delay: 5

        - name: Install Chrome
          become: true
          ansible.builtin.apt:
            deb: "/tmp/google-chrome-stable_current_amd64.deb"
            state: present
