- name: ZSH config file
  hosts: localhost

  vars:
    files:
      - src: "files/.zshrc"
        dest: "~/"
      - src: "files/.tmux.conf"
        dest: "~/"
      - src: "files/config/alacritty.toml"
        dest: "~/.config/alacritty/"
  tasks:

    - name: Copy files if they don't exist
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: "0644"
        force: false
      loop: "{{ files }}"
