- name: Create some folders
  hosts: localhost

  vars:
    folders:
      - "~/bin"
      - "~/apps"
      - "~/.ssh"

  tasks:
    - name: Create folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ folders }}"
