- name: Create some folders
  hosts: localhost

  tasks:
    - name: Create a '~/bin' folder
      ansible.builtin.file:
        path: "~/bin"
        state: directory
        mode: "0755"

    - name: Create rclone config folder
      ansible.builtin.file:
        path: "~/.config/rclone"
        state: directory
        mode: "0755"
