- name: Configure git
  hosts: localhost

  tasks:
    - name: Set global git user and email
      community.general.git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
        state: present
      loop:
        - { name: "user.name", value: "{{ git_user }}" }
        - { name: "user.email", value: "{{ git_email }}" }
