- name: Install k8s related packages
  hosts: localhost
  become: false

  tasks:
    - name: Install podman
      ansible.builtin.apt:
        name: podman
        state: present
      become: true

    - name: Check if minikube binary is installed
      ansible.builtin.stat:
        path: /usr/bin/minikube
      register: minikube_binary_installed

    - name: Install minikube
      when: not minikube_binary_installed.stat.exists
      block:

        - name: Install minikube
          ansible.builtin.apt:
            deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
            state: present
            update_cache: true
          become: true

        - name: Add minikube completion to zsh
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.zshrc"
            line: "source <(minikube completion zsh)"
            state: present

    - name: Install kubectl
      block:
        - name: Install kubectl
          community.general.snap:
            name: kubectl
            channel: latest/stable
            classic: true
            state: present
          become: true

        - name: Add kubectl auto-completion to zsh
          ansible.builtin.lineinfile:
            path: "{{ ansible_env.HOME }}/.zshrc"
            line: "source <(kubectl completion zsh)"
            state: present
