- name: Set up local Ubuntu machine
  hosts: localhost

- name: Install oh-my-zsh
  ansible.builtin.import_playbook: omzsh.yml

- name: Install brew
  ansible.builtin.import_playbook: brew.yml

- name: Install folders
  ansible.builtin.import_playbook: folders.yml

- name: Install dotfiles
  ansible.builtin.import_playbook: dotfiles.yml

- name: Install cheat
  ansible.builtin.import_playbook: cheat.yml

- name: Install packages and applications
  ansible.builtin.import_playbook: packages.yml

- name: Install Python
  ansible.builtin.import_playbook: python.yml

- name: Install Java
  ansible.builtin.import_playbook: java.yml
