- name: Set up local Ubuntu machine
  hosts: localhost

- name: Install oh-my-zsh
  ansible.builtin.import_playbook: omzsh.yml
  tags: fast, minimal

- name: Install brew
  ansible.builtin.import_playbook: brew.yml
  tags: slow, minimal

- name: Install folders
  ansible.builtin.import_playbook: folders.yml
  tags: fast, minimal

- name: Install files
  ansible.builtin.import_playbook: files.yml
  tags: fast, minimal

- name: Install cheat
  ansible.builtin.import_playbook: cheat.yml
  tags: fast, minimal

- name: Install Rust
  ansible.builtin.import_playbook: rust.yml
  tags: slow, minimal

- name: Install packages and applications
  ansible.builtin.import_playbook: packages.yml
  tags: slow, minimal

- name: Install Chrome
  ansible.builtin.import_playbook: chrome.yml
  tags: slow

- name: Install Python
  ansible.builtin.import_playbook: python.yml
  tags: slow

- name: Install Java
  ansible.builtin.import_playbook: java.yml
  tags: slow

- name: Add known hosts
  ansible.builtin.import_playbook: known_hosts.yml
  tags: fast, minimal

- name: Install Docker
  ansible.builtin.import_playbook: docker.yml
  tags: slow

- name: Install k8s tools
  ansible.builtin.import_playbook: k8s.yml
  tags: slow

- name: Install javascript tools
  ansible.builtin.import_playbook: javascript.yml
  tags: slow

- name: Install AstroNVim
  ansible.builtin.import_playbook: astronvim.yml
  tags: slow

- name: Install Logseq
  ansible.builtin.import_playbook: logseq.yml
  tags: slow
