- name: Bootstrap - gather facts for OS detection
  hosts: localhost
  gather_facts: true

- name: My clone of cheat repo
  ansible.builtin.import_playbook: cheat-repo.yml

- name: Set up openssh-server
  ansible.builtin.import_playbook: openssh.yml
  when: ansible_system == "Linux"
