- name: Playbooks to run after installing secrets.
  hosts: localhost

- name: My clone of cheat repo
  when: ssh_folder.stat.exists
  ansible.builtin.import_playbook: cheat-repo.yml

- name: Set up openssh-server
  ansible.builtin.import_playbook: openssh.yml
