- name: Install additional packages on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  vars:
    
    homebrew_packages:
      - fzf
      - ripgrep
      - just

    cargo_packages:
      - package: "watchexec-cli"
        binary: "watchexec"
      - package: "tree-sitter-cli"
        binary: "tree-sitter"
      - package: "du-dust"
        binary: "dust"
      - package: "bottom"
        binary: "btm"
      - package: "cargo-updater"
        binary: "cargo-updater"
      - package: "bat"
        binary: "bat"
      - package: "exa"
        binary: "exa"

  tasks:
    
    - name: Install homebrew packages
      become: false # Run tasks as normal user
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_packages }}"

    - name: Install fzf key bindings and fuzzy completion
      become: false # Run tasks as normal user
      ansible.builtin.command:
        cmd: /home/linuxbrew/.linuxbrew/opt/fzf/install --all
        creates: ~/.fzf.zsh

    - name: Install cargo packages
      become: false # Run tasks as normal user
      ansible.builtin.command:
        cmd: ~/.cargo/bin/cargo binstall -y {{ item.package }}
        creates: ~/.cargo/bin/{{ item.binary }}
      loop: "{{ cargo_packages }}"
