- name: Install additional packages on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  tasks:

    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - git
          - geany
          - git-gui
          - vim
          - meld
          - htop
          - keepass2
          - python3-pip
          - python3-venv
          - rclone
          - xclip
          - p7zip-full
          - ffmpeg
          - tldr
          - tmux
          - simplescreenrecorder
          - xournalpp
        state: present
        update_cache: true

    - name: Install homebrew packages
      become: false # Run tasks as normal user
      block:
        - name: Install fzf
          community.general.homebrew:
            name:
              - fzf
            state: present

        - name: Install useful key bindings and fuzzy completion
          ansible.builtin.command: /home/linuxbrew/.linuxbrew/opt/fzf/install -all
          register: fzf_install
          failed_when: fzf_install.rc != 0 and fzf_install.rc != 1
          changed_when: false
