- name: Install additional packages on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  tasks:

    - name: Repo for Keepass2
      ansible.builtin.apt_repository:
        repo: ppa:ubuntuhandbook1/keepass2
        state: present

    - name: Install standard apt packages
      ansible.builtin.apt:
        name:
          - git
          - geany
          - git-gui
          - vim
          - meld
          - htop
          - keepass2
          - python3-pip
          - python3-venv
          - python3-apt
          - rclone
          - xclip
          - p7zip-full
          - ffmpeg
          - tldr
          - tmux
          - simplescreenrecorder
          - xournalpp
        state: present
        autoremove: true
        update_cache: true

    - name: Install snap packages
      become: true # Run tasks as sudo
      community.general.snap:
        name:
          - multipass
          - code
          - spotify
          - firefox
        state: present
        classic: true

    - name: Update firefox to latest version # above snap install will not update to latest version if already installed
      block:
        - name: Kill running firefox processes
          become: true # Run tasks as sudo
          ansible.builtin.command: pkill firefox
          changed_when: false

        - name: Update firefox package
          become: true # Run tasks as sudo
          ansible.builtin.command: snap refresh firefox
          changed_when: false


    - name: Install homebrew packages
      become: false # Run tasks as normal user
      block:
        - name: Install fzf
          community.general.homebrew:
            name:
              - fzf
            state: present

        - name: Install useful key bindings and fuzzy completion
          ansible.builtin.command: /home/linuxbrew/.linuxbrew/opt/fzf/install -all
          register: fzf_install
          failed_when: fzf_install.rc != 0 and fzf_install.rc != 1
          changed_when: false

    - name: Intall Alacritty
      block:
        - name: Add Alacritty repository
          ansible.builtin.apt_repository:
            repo: ppa:aslatter/ppa
            state: present
            update_cache: true

        - name: Install Alacritty
          ansible.builtin.apt:
            name: alacritty
            state: present
