- name: Install additional packages on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  vars:
    apt_packages:
      - build-essential
      - git
      - vim
      - htop
      - python3-pip
      - python3-venv
      - python3-apt
      - rclone
      - xclip
      - p7zip-full
      - tldr
      - tmux
      - curl

  tasks:
    - name: Install standard apt packages - server
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages }}"
