- name: Install additional packages on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install packages
      ansible.builtin.apt:
        name:
          - git
          - geany
          - git-gui
          - vim
          - meld
          - htop
          - keepass2
          - python3-pip
          - python3-venv
          - rclone
          - xclip
          - p7zip-full
          - ffmpeg
          - tldr
          - tmux
          - simplescreenrecorder
          - xournalpp
        state: present
