- name: Install additional packages on Ubuntu
  hosts: localhost 
  become: yes  # Run tasks as sudo

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name:
          - git
          - geany
        state: present
