- name: Install additional packages on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  vars:
    apt_packages:
      - geany
      - git-gui
      - meld
      - keepass2
      - simplescreenrecorder
      - xournalpp

    snap_packages:
      - code
      - spotify
      - multipass
      - firefox

  tasks:
    - name: Repo for Keepass2
      ansible.builtin.apt_repository:
        repo: ppa:ubuntuhandbook1/keepass2
        state: present

    - name: Install standard apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages }}"

    - name: Install and config snap packages
      block:
        - name: Install snap packages
          become: true # Run tasks as sudo
          community.general.snap:
            name: "{{ item }}"
            state: present
            classic: true
          loop: "{{ snap_packages }}"

        - name: Config line for snap to enable application search
          become: true
          ansible.builtin.lineinfile:
            create: true
            path: /etc/zsh/zprofile
            line: "emulate sh -c 'source /etc/profile.d/apps-bin-path.sh'"
            mode: "0644"
            state: present

    - name: Update firefox to latest version # above snap install will not update to latest version if already installed
      block:
        - name: Kill running firefox processes
          become: true # Run tasks as sudo
          ansible.builtin.command: pkill firefox
          changed_when: false
          failed_when: false

        - name: Update firefox package
          become: true # Run tasks as sudo
          ansible.builtin.command: snap refresh firefox
          changed_when: false

    - name: Install Alacritty
      become: true # Run tasks as sudo. It happened that at this point it acted as normal user. Not sure why.
      block:
        - name: Add Alacritty repository
          ansible.builtin.apt_repository:
            repo: ppa:aslatter/ppa
            state: present
            update_cache: true

        - name: Install Alacritty
          ansible.builtin.apt:
            name: alacritty
            state: present
