- name: Install additional packages on Ubuntu
  hosts: localhost
  become: true # Run tasks as sudo

  vars:
    apt_packages:
      - libfuse2t64 # required on Ubuntu 24.04 for AppImages eg cursor
      - dconf-editor
      - gnome-tweaks
      - gnome-shell-extensions
      - ffmpeg

  tasks:
    - name: Install standard apt packages - desktop
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages }}"
