- name: Install extended server packages
  hosts: localhost
  become: false  # Homebrew and cargo run as the normal user.

  tasks:
    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ ext_server_brew_packages }}"
        state: present

    - name: Install fzf key bindings and fuzzy completion
      ansible.builtin.shell:
        cmd: "$({{ brew_bin }} --prefix)/opt/fzf/install --all"
        creates: ~/.fzf.zsh

    - name: Install cargo packages
      ansible.builtin.command:
        cmd: ~/.cargo/bin/cargo binstall -y {{ item.package }}
        creates: ~/.cargo/bin/{{ item.binary }}
      loop: "{{ cargo_packages }}"
