- name: Install additional packages on Ubuntu
  hosts: localhost
  become: false # Run tasks as sudo

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install packages
      ansible.builtin.apt:
        name:
          - git
          - geany
        state: present
