- name: Install Python (uv)
  hosts: localhost

  vars:
    python_versions:
      - "3.11"
      - "3.12"
      - "3.13"

  tasks:
    - name: Install uv
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          curl -fsSL https://astral.sh/uv/install.sh | sh
        executable: /bin/zsh
        creates: "~/.local/bin/uv"

    - name: Get installed Python versions
      ansible.builtin.shell:
        cmd: "~/.local/bin/uv python list --only-installed"
        executable: /bin/zsh
      register: installed_python_versions
      changed_when: true

    - name: Install Python versions with uv
      ansible.builtin.shell:
        cmd: "~/.local/bin/uv python install {{ item }}"
        executable: /bin/zsh
      when: item not in installed_python_versions.stdout
      loop: "{{ python_versions }}"
      changed_when: true
