- name: Install Rust
  hosts: localhost

  tasks:
    - name: Check if Rust is installed
      ansible.builtin.stat:
        path: ~/.cargo/bin/rustup
      register: rustup_installed

    - name: Install Rust
      when: not rustup_installed.stat.exists
      block:
        - name: Install Rust dependencies
          become: true
          ansible.builtin.apt:
            name:
              - curl
              - build-essential
            state: present

        - name: Download install script
          ansible.builtin.get_url:
            url: https://sh.rustup.rs
            dest: /tmp/rustup.sh
            mode: "u=rwx,g=rx,o=rx"

        - name: Install Rust
          ansible.builtin.shell:
            cmd: |
              /tmp/rustup.sh -y
            creates: ~/.cargo/bin/rustup

        - name: Create Zsh autocomplition directory
          ansible.builtin.file:
            path: ~/.zfunc
            state: directory
            mode: "0755"

        - name: Zsh autocomplition for Rust
          ansible.builtin.shell:
            cmd: "~/.cargo/bin/rustup completions zsh > ~/.zfunc/_rustup"
            creates: ~/.zfunc/_rustup
