- name: Copy dot files
  hosts: localhost

  tasks:
    - name: Copy ssh files and add private keys to ssh-agent
      block:

        - name: Ssh files
          ansible.builtin.copy:
            src: "secrets/ssh/"
            dest: "{{ ansible_env.HOME }}/.ssh/"
            mode: "0600"

        - name: Add paterit ssh key to ssh-agent # noqa command-instead-of-shell
          ansible.builtin.shell: |
            eval "$(ssh-agent)"
            ssh-add {{ ansible_env.HOME }}/.ssh/id_rsa_paterit
          register: ssh_add_paterit
          failed_when: ssh_add_paterit.rc != 0
          changed_when: false

        - name: Add nc ssh key to ssh-agent # noqa command-instead-of-shell
          ansible.builtin.shell: |
            eval "$(ssh-agent)"
            ssh-add {{ ansible_env.HOME }}/.ssh/nc_github_ws
          register: ssh_add_nc
          failed_when: ssh_add_nc.rc != 0
          changed_when: false

    - name: Rclone config file
      ansible.builtin.copy:
        src: "secrets/rclone/rclone.conf"
        dest: "{{ ansible_env.HOME }}/.config/rclone/"
        mode: "0644"
